# Generated by Django 5.0.4 on 2024-05-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_form_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
