# Generated by Django 5.0.4 on 2024-05-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_form_number_alter_form_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='number',
        ),
    ]
